Macro FIX2INT now requires parenthesis when used in a switch-statement
Fixes ruby-forge bug #28215:
  dtrace_probe.c: In function ‘dtraceprobe_probe_offset’:
  dtrace_probe.c:254: error: expected ‘(’ before ‘rb_fix2int’